source 'https://rubygems.org'

gem 'faraday-cookie_jar'
gem 'nokogiri'
gem 'oxcelix'
gem 'pupa', git: 'https://github.com/jpmckinney/pupa-ruby.git'
gem 'rake'
gem 'safe_yaml'
gem 'spreadsheet'
gem 'unicode_utils'
gem 'whos_got_dirt', git: 'https://github.com/influencemapping/whos_got_dirt-gem.git'
